services:
  backend:
    container_name: backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    # user: "1000:1000"  # Permissões do backend
    ports:
      - "3000:3000"
    volumes:
      - .:/backend:delegated
      # - ./node_modules:/backend/node_modules  # Corrige o volume de dependências
    depends_on:
      - db
      - migration
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile.database
    restart: always
    container_name: db
    volumes:
      - dbdata:/var/lib/postgresql/data  # Mapeia um diretório local (se preferir persistir localmente)
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD=md5  # Use autenticação com senha, mais seguro

  migration:
    container_name: migration
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile.migration
    depends_on:
      - db
    command: sh -c 'until nc -z db 5432; do echo waiting for db; sleep 1; done; npx prisma migrate deploy'

  studio:
    container_name: studio
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile.studio
    ports:
      - "5555:5555"
    depends_on:
      - db
      - migration
      - backend
    environment:
      - DATABASE_URL=${DATABASE_URL}

volumes:
  dbdata:  # Volume para o banco de dados
